// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKaNCLD6Hm8-NUQbTRXJnmd6uLn0PMBXY',
    appId: '1:762443577973:web:f23cfbaade799c5a24563c',
    messagingSenderId: '762443577973',
    projectId: 'intern-projects-f9089',
    authDomain: 'intern-projects-f9089.firebaseapp.com',
    storageBucket: 'intern-projects-f9089.firebasestorage.app',
    measurementId: 'G-26LB8L3ZFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOx0xoxXIrivWnntCmJUgIm4YTTZJVWoQ',
    appId: '1:762443577973:android:89ba67ce92c53df824563c',
    messagingSenderId: '762443577973',
    projectId: 'intern-projects-f9089',
    storageBucket: 'intern-projects-f9089.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkZKaU8IHlIO0OMqWBk8ZBrW1leewYliU',
    appId: '1:762443577973:ios:75608e77a9f2fd0924563c',
    messagingSenderId: '762443577973',
    projectId: 'intern-projects-f9089',
    storageBucket: 'intern-projects-f9089.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkZKaU8IHlIO0OMqWBk8ZBrW1leewYliU',
    appId: '1:762443577973:ios:75608e77a9f2fd0924563c',
    messagingSenderId: '762443577973',
    projectId: 'intern-projects-f9089',
    storageBucket: 'intern-projects-f9089.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKaNCLD6Hm8-NUQbTRXJnmd6uLn0PMBXY',
    appId: '1:762443577973:web:da944b4056c91a0424563c',
    messagingSenderId: '762443577973',
    projectId: 'intern-projects-f9089',
    authDomain: 'intern-projects-f9089.firebaseapp.com',
    storageBucket: 'intern-projects-f9089.firebasestorage.app',
    measurementId: 'G-SXPWVQZE7M',
  );
}
